# Generated by peterkir/ki @ 2026-08-11T12:22:40Z (1c625e5)
# Source: https://github.com/peterkir/ki/tree/1c625e5bf28b0faf2fdd6dea61e93ca5db846105
# DO NOT EDIT — upgrade: curl -fsSL https://raw.githubusercontent.com/peterkir/ki/main/setup.sh | bash -s -- --upgrade

KI_SHA="1c625e5bf28b0faf2fdd6dea61e93ca5db846105"
KI_REF="main"
KI_TIMESTAMP="2026-08-11T12:22:40Z"
WRITE_TARGET=".copilot"
KI_NAME="bnd-workspace-template"
KI_DESC=""
KI_CAVEMAN="full"
KI_LANGS=("osgi" )
KI_SKILLS=("caveman" "system-analysis" "grilling" "to-spec" )
